from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor

from CustomPyQt import CustomQComboBox
from VideoWidget import Window
from Functions import ScreenSize, findnumber
from Popups import show_popup
from ReportWindow import Ui_ReportWindow
from CustomPyQt import CustomButton

screenwidth, screenheight = ScreenSize()

class Ui_CalculateWindow(object):
    def __init__(self, TextsForData):
        self.TextsForData = TextsForData
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.move(0,0)
        MainWindow.resize(screenwidth, screenheight)
        MainWindow.setMinimumSize(QtCore.QSize(int(screenwidth/2), int(screenheight/2)))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("""
    QWidget {
        background-color: #F0F0F0;
    }

    /* Customize the scroll bar */
    QScrollBar:vertical {
        background: #f0f0f0;
        width: 15px;
        margin: 0;
    }

    QScrollBar::handle:vertical {
        background: #bacada;
        min-height: 20px;
    }

    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
        background: none;
        height: 0;
        subcontrol-origin: margin;
    }

    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
        background: none;
    }

    QScrollBar:horizontal {
        background: #f0f0f0;
        height: 15px;
        margin: 0;
    }

    QScrollBar::handle:horizontal {
        background: #bacada;
        min-width: 20px;
    }

    QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {
        background: none;
        width: 0;
        subcontrol-origin: margin;
    }

    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {
        background: none;
    }

    /* Customize the combo box */
    QComboBox {
        background: white;
        border: 1px solid gray;
    }

    QComboBox QAbstractItemView {
        border: 1px solid gray;
        background-color: white;
    }
""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(546, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(546, 9999))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background: white;\n"
"    border: 0px solid gray;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        #self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1532, 527, 2425))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setHorizontalSpacing(0)
        self.gridLayout_19.setVerticalSpacing(15)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 81))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(8, 52, 96);\n"
"color: rgb(255, 255, 255);")
        self.label.setIndent(30)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(8, 52, 96);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 90, 148);")
        self.label_2.setIndent(30)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setVerticalSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(10)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_4.setLineWidth(0)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_6.setLineWidth(0)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.verticalLayout_25.addLayout(self.verticalLayout_3)
        self.comboBox_A = CustomQComboBox(self.frame_5)
        self.comboBox_A.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_A.setFont(font)
        self.comboBox_A.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_A.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboBox_A.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_A.setObjectName("comboBox_A")
        self.comboBox_A.addItem("")
        self.comboBox_A.addItem("")
        self.comboBox_A.addItem("")
        self.verticalLayout_25.addWidget(self.comboBox_A)
        self.gridLayout_6.addLayout(self.verticalLayout_25, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 290))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_5.setLineWidth(0)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(17, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_7.setLineWidth(0)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_8.setLineWidth(0)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setWordWrap(True)
        self.label_8.setIndent(0)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.comboBox_B1 = CustomQComboBox(self.frame_6)
        self.comboBox_B1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_B1.setFont(font)
        self.comboBox_B1.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_B1.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_B1.setObjectName("comboBox_B1")
        self.comboBox_B1.addItem("")
        self.comboBox_B1.addItem("")
        self.comboBox_B1.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_B1)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_9.setLineWidth(0)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setIndent(0)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_10.setLineWidth(0)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setWordWrap(True)
        self.label_10.setIndent(0)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.comboBox_B3 = CustomQComboBox(self.frame_6)
        self.comboBox_B3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_B3.setFont(font)
        self.comboBox_B3.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_B3.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_B3.setObjectName("comboBox_B3")
        self.comboBox_B3.addItem("")
        self.comboBox_B3.addItem("")
        self.comboBox_B3.addItem("")
        self.comboBox_B3.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_B3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_19.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setMinimumSize(QtCore.QSize(0, 40))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 90, 148);")
        self.label_11.setIndent(30)
        self.label_11.setObjectName("label_11")
        self.gridLayout_21.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_7, 2, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_8 = QtWidgets.QFrame(self.frame_10)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 99999))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setSpacing(10)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_12.setLineWidth(0)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_13.setLineWidth(0)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setIndent(0)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.verticalLayout_26.addLayout(self.verticalLayout_6)
        self.comboBox_C = CustomQComboBox(self.frame_8)
        self.comboBox_C.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_C.setFont(font)
        self.comboBox_C.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_C.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_C.setObjectName("comboBox_C")
        self.comboBox_C.addItem("")
        self.comboBox_C.addItem("")
        self.comboBox_C.addItem("")
        self.verticalLayout_26.addWidget(self.comboBox_C)
        self.gridLayout_8.addLayout(self.verticalLayout_26, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_14.setLineWidth(0)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.comboBox_D = CustomQComboBox(self.frame_9)
        self.comboBox_D.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_D.setFont(font)
        self.comboBox_D.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_D.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_D.setObjectName("comboBox_D")
        self.comboBox_D.addItem("")
        self.comboBox_D.addItem("")
        self.comboBox_D.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_D)
        self.gridLayout_9.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_20.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_10, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setMinimumSize(QtCore.QSize(0, 40))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 90, 148);")
        self.label_15.setIndent(30)
        self.label_15.setObjectName("label_15")
        self.gridLayout_19.addWidget(self.label_15, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_11.setMinimumSize(QtCore.QSize(104, 104))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setSpacing(10)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_16.setLineWidth(0)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_17.setLineWidth(0)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setIndent(0)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.verticalLayout_33.addLayout(self.verticalLayout_11)
        self.comboBox_E = CustomQComboBox(self.frame_11)
        self.comboBox_E.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_E.setFont(font)
        self.comboBox_E.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_E.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_E.setObjectName("comboBox_E")
        self.comboBox_E.addItem("")
        self.comboBox_E.addItem("")
        self.verticalLayout_33.addWidget(self.comboBox_E)
        self.gridLayout_10.addLayout(self.verticalLayout_33, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.frame_12)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_18.setLineWidth(0)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.comboBox_F = CustomQComboBox(self.frame_12)
        self.comboBox_F.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_F.setFont(font)
        self.comboBox_F.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_F.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_F.setObjectName("comboBox_F")
        self.comboBox_F.addItem("")
        self.comboBox_F.addItem("")
        self.comboBox_F.addItem("")
        self.verticalLayout_12.addWidget(self.comboBox_F)
        self.gridLayout_11.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_19.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setMinimumSize(QtCore.QSize(0, 40))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 90, 148);")
        self.label_19.setIndent(30)
        self.label_19.setObjectName("label_19")
        self.gridLayout_19.addWidget(self.label_19, 6, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 84))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSpacing(10)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.frame_13)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_20.setLineWidth(0)
        self.label_20.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.frame_13)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_21.setLineWidth(0)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_21.setIndent(0)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_14.addWidget(self.label_21)
        self.verticalLayout_34.addLayout(self.verticalLayout_14)
        self.comboBox_G = CustomQComboBox(self.frame_13)
        self.comboBox_G.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_G.setFont(font)
        self.comboBox_G.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_G.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_G.setObjectName("comboBox_G")
        self.comboBox_G.addItem("")
        self.comboBox_G.addItem("")
        self.comboBox_G.addItem("")
        self.verticalLayout_34.addWidget(self.comboBox_G)
        self.gridLayout_12.addLayout(self.verticalLayout_34, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_13)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_19.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_23 = QtWidgets.QLabel(self.frame_14)
        self.label_23.setMinimumSize(QtCore.QSize(0, 40))
        self.label_23.setMaximumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(8, 52, 96);\n"
"color: rgb(255, 255, 255);")
        self.label_23.setIndent(30)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_14)
        self.label_22.setMinimumSize(QtCore.QSize(0, 40))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(8, 52, 96);\n"
"color: rgb(255, 255, 255);")
        self.label_22.setIndent(0)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 0, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_14)
        self.gridLayout_19.addLayout(self.horizontalLayout_7, 8, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_24 = QtWidgets.QLabel(self.frame_15)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_24.setLineWidth(0)
        self.label_24.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_16.addWidget(self.label_24)
        self.comboBox_H = CustomQComboBox(self.frame_15)
        self.comboBox_H.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_H.setFont(font)
        self.comboBox_H.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_H.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_H.setObjectName("comboBox_H")
        self.comboBox_H.addItem("")
        self.comboBox_H.addItem("")
        self.comboBox_H.addItem("")
        self.comboBox_H.addItem("")
        self.verticalLayout_16.addWidget(self.comboBox_H)
        self.gridLayout_14.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_15)
        self.horizontalLayout_8.addLayout(self.verticalLayout_15)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.gridLayout_19.addLayout(self.horizontalLayout_8, 9, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(10)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.frame_16)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_25.setLineWidth(0)
        self.label_25.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_18.addWidget(self.label_25)
        self.comboBox_J = CustomQComboBox(self.frame_16)
        self.comboBox_J.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_J.setFont(font)
        self.comboBox_J.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_J.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_J.setObjectName("comboBox_J")
        self.comboBox_J.addItem("")
        self.comboBox_J.addItem("")
        self.comboBox_J.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox_J)
        self.gridLayout_15.addLayout(self.verticalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.frame_16)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.gridLayout_19.addLayout(self.horizontalLayout_9, 10, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_26 = QtWidgets.QLabel(self.frame_17)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_26.setLineWidth(0)
        self.label_26.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_20.addWidget(self.label_26)
        self.comboBox_K = CustomQComboBox(self.frame_17)
        self.comboBox_K.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_K.setFont(font)
        self.comboBox_K.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_K.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_K.setObjectName("comboBox_K")
        self.comboBox_K.addItem("")
        self.comboBox_K.addItem("")
        self.comboBox_K.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox_K)
        self.gridLayout_16.addLayout(self.verticalLayout_20, 0, 0, 1, 1)
        self.verticalLayout_19.addWidget(self.frame_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.gridLayout_19.addLayout(self.horizontalLayout_10, 11, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 214))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setSpacing(10)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_27 = QtWidgets.QLabel(self.frame_18)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_27.setLineWidth(0)
        self.label_27.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_35.addWidget(self.label_27)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_L = CustomQComboBox(self.frame_18)
        self.comboBox_L.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_L.setFont(font)
        self.comboBox_L.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_L.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_L.setObjectName("comboBox_L")
        self.comboBox_L.addItem("")
        self.comboBox_L.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_L)
        self.label_28 = QtWidgets.QLabel(self.frame_18)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_28.setLineWidth(0)
        self.label_28.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_28.setIndent(0)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_22.addWidget(self.label_28)
        self.verticalLayout_35.addLayout(self.verticalLayout_22)
        self.textEdit_For_L = QtWidgets.QTextEdit(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_For_L.sizePolicy().hasHeightForWidth())
        self.textEdit_For_L.setSizePolicy(sizePolicy)
        self.textEdit_For_L.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.textEdit_For_L.setFont(font)
        self.textEdit_For_L.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_For_L.setObjectName("textEdit_For_L")
        self.verticalLayout_35.addWidget(self.textEdit_For_L)
        self.gridLayout_17.addLayout(self.verticalLayout_35, 0, 0, 1, 1)
        self.verticalLayout_21.addWidget(self.frame_18)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.gridLayout_19.addLayout(self.horizontalLayout_11, 12, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(10)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_29 = QtWidgets.QLabel(self.frame_20)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_29.setLineWidth(0)
        self.label_29.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_24.addWidget(self.label_29)
        self.comboBox_M = CustomQComboBox(self.frame_20)
        self.comboBox_M.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_M.setFont(font)
        self.comboBox_M.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_M.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_M.setObjectName("comboBox_M")
        self.comboBox_M.addItem("")
        self.comboBox_M.addItem("")
        self.comboBox_M.addItem("")
        self.verticalLayout_24.addWidget(self.comboBox_M)
        self.gridLayout_18.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        self.verticalLayout_23.addWidget(self.frame_20)
        self.horizontalLayout_12.addLayout(self.verticalLayout_23)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.gridLayout_22.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_19, 13, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(10)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_31 = QtWidgets.QLabel(self.frame_23)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_31.setLineWidth(0)
        self.label_31.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_28.addWidget(self.label_31)
        self.comboBox_N = CustomQComboBox(self.frame_23)
        self.comboBox_N.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_N.setFont(font)
        self.comboBox_N.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_N.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_N.setObjectName("comboBox_N")
        self.comboBox_N.addItem("")
        self.comboBox_N.addItem("")
        self.comboBox_N.addItem("")
        self.verticalLayout_28.addWidget(self.comboBox_N)
        self.gridLayout_24.addLayout(self.verticalLayout_28, 0, 0, 1, 1)
        self.verticalLayout_27.addWidget(self.frame_23)
        self.horizontalLayout_14.addLayout(self.verticalLayout_27)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.gridLayout_19.addLayout(self.horizontalLayout_14, 14, 0, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 184))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setSpacing(10)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_34 = QtWidgets.QLabel(self.frame_27)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_34.setLineWidth(0)
        self.label_34.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_36.addWidget(self.label_34)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.comboBox_P = CustomQComboBox(self.frame_27)
        self.comboBox_P.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_P.setFont(font)
        self.comboBox_P.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_P.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_P.setObjectName("comboBox_P")
        self.comboBox_P.addItem("")
        self.comboBox_P.addItem("")
        self.comboBox_P.addItem("")
        self.verticalLayout_32.addWidget(self.comboBox_P)
        self.label_35 = QtWidgets.QLabel(self.frame_27)
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_35.setLineWidth(0)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_35.setIndent(0)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_32.addWidget(self.label_35)
        self.verticalLayout_36.addLayout(self.verticalLayout_32)
        self.textEdit_For_P = QtWidgets.QTextEdit(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_For_P.sizePolicy().hasHeightForWidth())
        self.textEdit_For_P.setSizePolicy(sizePolicy)
        self.textEdit_For_P.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.textEdit_For_P.setFont(font)
        self.textEdit_For_P.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_For_P.setObjectName("textEdit_For_P")
        self.verticalLayout_36.addWidget(self.textEdit_For_P)
        self.gridLayout_23.addLayout(self.verticalLayout_36, 0, 0, 1, 1)
        self.verticalLayout_31.addWidget(self.frame_27)
        self.horizontalLayout_16.addLayout(self.verticalLayout_31)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.gridLayout_29.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_26, 15, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem23)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_25 = QtWidgets.QFrame(self.frame_24)
        self.frame_25.setMinimumSize(QtCore.QSize(0, 184))
        self.frame_25.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_37.setSpacing(10)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_32 = QtWidgets.QLabel(self.frame_25)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_32.setLineWidth(0)
        self.label_32.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_37.addWidget(self.label_32)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.comboBox_Q = CustomQComboBox(self.frame_25)
        self.comboBox_Q.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.comboBox_Q.setFont(font)
        self.comboBox_Q.setStyleSheet("color: rgb(7, 52, 96);")
        self.comboBox_Q.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_Q.setObjectName("comboBox_Q")
        self.comboBox_Q.addItem("")
        self.comboBox_Q.addItem("")
        self.comboBox_Q.addItem("")
        self.comboBox_Q.addItem("")
        self.verticalLayout_30.addWidget(self.comboBox_Q)
        self.label_33 = QtWidgets.QLabel(self.frame_25)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(7, 52, 96);")
        self.label_33.setLineWidth(0)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_33.setIndent(0)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_30.addWidget(self.label_33)
        self.verticalLayout_37.addLayout(self.verticalLayout_30)
        self.textEdit_For_Q = QtWidgets.QTextEdit(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_For_Q.sizePolicy().hasHeightForWidth())
        self.textEdit_For_Q.setSizePolicy(sizePolicy)
        self.textEdit_For_Q.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.textEdit_For_Q.setFont(font)
        self.textEdit_For_Q.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_For_Q.setObjectName("textEdit_For_Q")
        self.verticalLayout_37.addWidget(self.textEdit_For_Q)
        self.gridLayout_25.addLayout(self.verticalLayout_37, 0, 0, 1, 1)
        self.verticalLayout_29.addWidget(self.frame_25)
        self.horizontalLayout_15.addLayout(self.verticalLayout_29)
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem24)
        self.gridLayout_27.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_24, 16, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(600, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 12, 9, 12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancel = CustomButton(parent=self.frame_3, start_color=QColor(121, 156, 191), end_color=QColor(156,188,220), pressed_color=QColor(88,133,177))
        self.cancel.setMinimumSize(QtCore.QSize(0, 50))
        self.cancel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.gridLayout_2.addWidget(self.cancel, 0, 0, 1, 1)
        self.pushButton_Calculate = CustomButton(parent=self.frame_3, start_color=QColor(0, 163, 26), end_color=QColor(69,188,88), pressed_color=QColor(70,158,84))
        self.pushButton_Calculate.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Calculate.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Calculate.setFont(font)
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.gridLayout_2.addWidget(self.pushButton_Calculate, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.frame_for_video = QtWidgets.QFrame(self.frame)
        #self.frame_for_video.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_for_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_video.setObjectName("frame_for_video")
        self.gridLayout_video = QtWidgets.QGridLayout(self.frame_for_video)
        self.gridLayout_video.setContentsMargins(0, 0, 0, 0)  # Set contents margins to 0
        self.gridLayout_video.setSpacing(0)  # Set spacing to 0
        self.gridLayout_video.setObjectName("gridLayout_video")
        self.window_widget = Window(self.TextsForData,self.centralwidget)
        self.gridLayout_video.addWidget(self.window_widget)
        self.gridLayout.addWidget(self.frame_for_video, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.comboBox_B1.currentIndexChanged.connect(self.disable_b3)
        self.comboBox_B3.currentIndexChanged.connect(self.disable_b1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_Calculate.clicked.connect(self.disable_B1_B3)
        self.retranslateUi(MainWindow)
        self.getvalue()
        self.comboBox_L.currentIndexChanged.connect(self.disableTexteditL)
        self.comboBox_P.currentIndexChanged.connect(self.disableTexteditP)
        self.comboBox_Q.currentIndexChanged.connect(self.disableTexteditQ)
        self.disableTexteditL(self.comboBox_L.currentIndex())
        self.disableTexteditP(self.comboBox_P.currentIndex())
        self.disableTexteditQ(self.comboBox_Q.currentIndex())
        self.cancel.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def disableTexteditL(self,index):
        if index==1:
            self.textEdit_For_L.setEnabled(True)
        else:
            self.textEdit_For_L.setEnabled(False)

    def disableTexteditP(self,index):
        if index==2:
            self.textEdit_For_P.setEnabled(True)
        else:
            self.textEdit_For_P.setEnabled(False)
    def disableTexteditQ(self,index):
        if index==2:
            self.textEdit_For_Q.setEnabled(True)
        elif index==3:
            self.textEdit_For_Q.setEnabled(True)
        else:
            self.textEdit_For_Q.setEnabled(False)
    
    def disable_b3(self, index):
        # Change the condition below to match the options you want to disable comboBox_B3
        if index != 0:  # Replace 1 with the index of the option you want to disable comboBox_B3
            self.comboBox_B3.setDisabled(True)
        else:
            self.comboBox_B3.setDisabled(False)
    def disable_b1(self, index):
        # Change the condition below to match the options you want to disable comboBox_B3
        if index != 0:  # Replace 1 with the index of the option you want to disable comboBox_B3
            self.comboBox_B1.setDisabled(True)
        else:
            self.comboBox_B1.setDisabled(False)

    def disable_B1_B3(self):
        self.set_combo_box()
        if (((self.TextsForData.get_B1()==None) and (self.TextsForData.get_B3()==None)) or (self.TextsForData.get_B1()!=None) and (self.TextsForData.get_B3()!=None)):
            show_popup()
        else:
            self.openWindow()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Observer\'s"))
        self.label_3.setText(_translate("MainWindow", "Assessment"))
        self.label_2.setText(_translate("MainWindow", "Back"))
        self.label_4.setText(_translate("MainWindow", "A - When performing the task, is the back"))
        self.label_6.setText(_translate("MainWindow", "      (select worse case situation)"))
        self.comboBox_A.setItemText(0, _translate("MainWindow", "     A1 Almost Neutral"))
        self.comboBox_A.setItemText(1, _translate("MainWindow", "     A2 Moderately flexed or twisted or side bent?"))
        self.comboBox_A.setItemText(2, _translate("MainWindow", "     A3 Excessively flexed or twisted or side bent?"))
        self.label_5.setText(_translate("MainWindow", "B - Select ONLY ONE of the following task options:"))
        self.label_7.setText(_translate("MainWindow", "EITHER"))
        self.label_8.setText(_translate("MainWindow", "For seated or standing staionary tasks. Does the back remain in a static position most of the time?"))
        self.comboBox_B1.setItemText(0, _translate("MainWindow", "     None"))
        self.comboBox_B1.setItemText(1, _translate("MainWindow", "     B1 No"))
        self.comboBox_B1.setItemText(2, _translate("MainWindow", "     B2 Yes"))
        self.label_9.setText(_translate("MainWindow", "OR"))
        self.label_10.setText(_translate("MainWindow", "For lifting, pushing/pulling and carrying tasks (i.e moving a load). Is the movement of the back"))
        self.comboBox_B3.setItemText(0, _translate("MainWindow", "     None"))
        self.comboBox_B3.setItemText(1, _translate("MainWindow", "     B3 Infrequent (around x3 per min. or less)"))
        self.comboBox_B3.setItemText(2, _translate("MainWindow", "     B4 Frequent (around x8 per min.)"))
        self.comboBox_B3.setItemText(3, _translate("MainWindow", "     B5 Very frequent (around x12 per day or more)"))
        self.label_11.setText(_translate("MainWindow", "Shoulder / Arm"))
        self.label_12.setText(_translate("MainWindow", "C - When the task is performed, are the hands"))
        self.label_13.setText(_translate("MainWindow", "      (select worse case situation)"))
        self.comboBox_C.setItemText(0, _translate("MainWindow", "     C1 At or below waist height?"))
        self.comboBox_C.setItemText(1, _translate("MainWindow", "     C2 At about chest height?"))
        self.comboBox_C.setItemText(2, _translate("MainWindow", "     C3 At or above shoulder height?"))
        self.label_14.setText(_translate("MainWindow", "D - Is the shoulder/arm movement"))
        self.comboBox_D.setItemText(0, _translate("MainWindow", "     D1 Infrequent (some intermittent movement)?"))
        self.comboBox_D.setItemText(1, _translate("MainWindow", "     D2 Frequent (regular movement with some pauses)"))
        self.comboBox_D.setItemText(2, _translate("MainWindow", "     D3 Very frequent (almost continues movement)"))
        self.label_15.setText(_translate("MainWindow", "Wrist / Hand"))
        self.label_16.setText(_translate("MainWindow", "E - Is the task performed with"))
        self.label_17.setText(_translate("MainWindow", "      (select worse case situation)"))
        self.comboBox_E.setItemText(0, _translate("MainWindow", "     E1 An almost straight wrist?"))
        self.comboBox_E.setItemText(1, _translate("MainWindow", "     E2 A deviated or bent wrist?"))
        self.label_18.setText(_translate("MainWindow", "F - Are similar motion patterns repeated"))
        self.comboBox_F.setItemText(0, _translate("MainWindow", "     F1 10 times per minute or less"))
        self.comboBox_F.setItemText(1, _translate("MainWindow", "     F2 11 to 20 times per minute"))
        self.comboBox_F.setItemText(2, _translate("MainWindow", "     F3 More than 20 times per minute"))
        self.label_19.setText(_translate("MainWindow", "Neck"))
        self.label_20.setText(_translate("MainWindow", "G - When performing the task, is the head/neck bent or twisted"))
        self.label_21.setText(_translate("MainWindow", "      (select worse case situation)"))
        self.comboBox_G.setItemText(0, _translate("MainWindow", "     G1 No"))
        self.comboBox_G.setItemText(1, _translate("MainWindow", "     G2 Yes, occasionally"))
        self.comboBox_G.setItemText(2, _translate("MainWindow", "     G3 Yes, continuously"))
        self.label_23.setText(_translate("MainWindow", "Worker\'s"))
        self.label_22.setText(_translate("MainWindow", "Assessment"))
        self.label_24.setText(_translate("MainWindow", "H - Is the maximum weight handled MANUALLY BY YOU in the task?"))
        self.comboBox_H.setItemText(0, _translate("MainWindow", "     H1 Light (5 kg or less)"))
        self.comboBox_H.setItemText(1, _translate("MainWindow", "     H2 Moderate (6 to 10 kg)"))
        self.comboBox_H.setItemText(2, _translate("MainWindow", "     H3 Heavy (11 to 20 kg)"))
        self.comboBox_H.setItemText(3, _translate("MainWindow", "     H4 Very heavy (more than 20 kg)"))
        self.label_25.setText(_translate("MainWindow", "J - On average, how much time do you spend per day on this task?"))
        self.comboBox_J.setItemText(0, _translate("MainWindow", "     J1 Less than 2 hours"))
        self.comboBox_J.setItemText(1, _translate("MainWindow", "     J2 2 to 4 hours"))
        self.comboBox_J.setItemText(2, _translate("MainWindow", "     J3 More than 4 hours"))
        self.label_26.setText(_translate("MainWindow", "K - When performing this task, is the maximum force level exerted by one hand?"))
        self.comboBox_K.setItemText(0, _translate("MainWindow", "     K1 Low (e.g less than 1 kg)"))
        self.comboBox_K.setItemText(1, _translate("MainWindow", "     K2 Medium (e.g 1 to 4 kg)"))
        self.comboBox_K.setItemText(2, _translate("MainWindow", "     K3 High (e.g more than 4 kg)"))
        self.label_27.setText(_translate("MainWindow", "L - Is the visual demand of this task"))
        self.comboBox_L.setItemText(0, _translate("MainWindow", "     L1 Low (almost no need to view fine details)"))
        self.comboBox_L.setItemText(1, _translate("MainWindow", "     *L2 High (need to view some fine details)"))
        self.label_28.setText(_translate("MainWindow", "      (If high, please give details in the box below.)"))
        self.label_29.setText(_translate("MainWindow", "M - At work do you drive a vehicle for"))
        self.comboBox_M.setItemText(0, _translate("MainWindow", "     M1 Less than one hour per day or never?"))
        self.comboBox_M.setItemText(1, _translate("MainWindow", "     M2 Between 1 and 4 hours per day?"))
        self.comboBox_M.setItemText(2, _translate("MainWindow", "     M3 More than 4 hours per day?"))
        self.label_31.setText(_translate("MainWindow", "N - At work do you use vibrating tools for"))
        self.comboBox_N.setItemText(0, _translate("MainWindow", "     N1 Less than one hour per day or never?"))
        self.comboBox_N.setItemText(1, _translate("MainWindow", "     N2 Between 1 and 4 hours per day?"))
        self.comboBox_N.setItemText(2, _translate("MainWindow", "     N3 More than 4 hours per day?"))
        self.label_34.setText(_translate("MainWindow", "P - Do you have difficulty keeping up with this work?"))
        self.comboBox_P.setItemText(0, _translate("MainWindow", "     P1 Never"))
        self.comboBox_P.setItemText(1, _translate("MainWindow", "     P2 Sometimes"))
        self.comboBox_P.setItemText(2, _translate("MainWindow", "     P3 Often"))
        self.label_35.setText(_translate("MainWindow", "      (If often, please give details in the box below.)"))
        self.label_32.setText(_translate("MainWindow", "Q - In general, how do you find this job"))
        self.comboBox_Q.setItemText(0, _translate("MainWindow", "     Q1 Not at all stressfull?"))
        self.comboBox_Q.setItemText(1, _translate("MainWindow", "     Q2 Mildly stressfull?"))
        self.comboBox_Q.setItemText(2, _translate("MainWindow", "     Q3 Moderatly stressfull?"))
        self.comboBox_Q.setItemText(3, _translate("MainWindow", "     Q4 Very stressfull?"))
        self.label_33.setText(_translate("MainWindow", "      (If moderatly or very, please give details in the box below.)"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "Calculate"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))

    def getvalue(self):
        if self.TextsForData.get_A()!="None":
            self.comboBox_A.setCurrentIndex(int(self.TextsForData.get_A())-1)
            if self.TextsForData.get_B1()=="None":
                self.comboBox_B3.setCurrentIndex(int(self.TextsForData.get_B3())-2)
            elif self.TextsForData.get_B3()=="None":
                self.comboBox_B1.setCurrentIndex(int(self.TextsForData.get_B1()))
            self.comboBox_C.setCurrentIndex(int(self.TextsForData.get_C())-1)
            self.comboBox_D.setCurrentIndex(int(self.TextsForData.get_D())-1)
            self.comboBox_E.setCurrentIndex(int(self.TextsForData.get_E())-1)
            self.comboBox_F.setCurrentIndex(int(self.TextsForData.get_F())-1)
            self.comboBox_G.setCurrentIndex(int(self.TextsForData.get_G())-1)
            self.comboBox_H.setCurrentIndex(int(self.TextsForData.get_H())-1)
            self.comboBox_J.setCurrentIndex(int(self.TextsForData.get_J())-1)
            self.comboBox_K.setCurrentIndex(int(self.TextsForData.get_K())-1)
            self.comboBox_L.setCurrentIndex(int(self.TextsForData.get_L())-1)
            self.comboBox_M.setCurrentIndex(int(self.TextsForData.get_M())-1)
            self.comboBox_N.setCurrentIndex(int(self.TextsForData.get_N())-1)
            self.comboBox_P.setCurrentIndex(int(self.TextsForData.get_P())-1)
            self.comboBox_Q.setCurrentIndex(int(self.TextsForData.get_Q())-1)
            if self.TextsForData.get_LL()!="None":
                self.textEdit_For_L.insertPlainText(self.TextsForData.get_LL())
            if self.TextsForData.get_LP()!="None":
                self.textEdit_For_P.insertPlainText(self.TextsForData.get_LP())
            if self.TextsForData.get_LQ()!="None":
                self.textEdit_For_Q.insertPlainText(self.TextsForData.get_LQ())

    def set_combo_box(self):
        self.TextsForData.set_A(findnumber(self.comboBox_A.currentText()))
        self.TextsForData.set_B1(findnumber(self.comboBox_B1.currentText()))
        self.TextsForData.set_B3(findnumber(self.comboBox_B3.currentText()))
        self.TextsForData.set_C(findnumber(self.comboBox_C.currentText()))
        self.TextsForData.set_D(findnumber(self.comboBox_D.currentText()))
        self.TextsForData.set_E(findnumber(self.comboBox_E.currentText()))
        self.TextsForData.set_F(findnumber(self.comboBox_F.currentText()))
        self.TextsForData.set_G(findnumber(self.comboBox_G.currentText()))
        self.TextsForData.set_H(findnumber(self.comboBox_H.currentText()))
        self.TextsForData.set_J(findnumber(self.comboBox_J.currentText()))
        self.TextsForData.set_K(findnumber(self.comboBox_K.currentText()))
        self.TextsForData.set_L(findnumber(self.comboBox_L.currentText()))
        self.TextsForData.set_M(findnumber(self.comboBox_M.currentText()))
        self.TextsForData.set_N(findnumber(self.comboBox_N.currentText()))
        self.TextsForData.set_P(findnumber(self.comboBox_P.currentText()))
        self.TextsForData.set_Q(findnumber(self.comboBox_Q.currentText()))
        if self.textEdit_For_L.isEnabled():
            self.TextsForData.set_LL(self.textEdit_For_L.toPlainText())
        if self.textEdit_For_P.isEnabled():
            self.TextsForData.set_LP(self.textEdit_For_P.toPlainText())
        if self.textEdit_For_Q.isEnabled():
            self.TextsForData.set_LQ(self.textEdit_For_Q.toPlainText())
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ReportWindow(self.TextsForData)
        self.ui.setupUi(self.window)
        self.window.show()